NumPy - Numerical Python

Advantages of Numpy Arrays:
    1. Allows several Mathematical Operations
    2. Faster operations


In [1]:
import numpy as np

List vs Numpy - Time Taken

In [7]:
# Time taken by list
python_list = [i for i in range(100000000)]
%time python_list = [i + 5 for i in python_list]

CPU times: total: 30.7 s
Wall time: 49.4 s


In [8]:
np_array = np.array([i for i in range(100000000)])
%time np_array += 5

CPU times: total: 500 ms
Wall time: 586 ms


In [6]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [11]:
# 1d array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [12]:
np_array.shape

(5,)

In [22]:
# 2d array
np_array2 = np.array([(1,2,3,4),
                      (1,2,3,4)])
np_array2.shape

(2, 4)

In [23]:
# floating point values in array
np_array3 = np.array([1.1, 23.3, 21.3],dtype=float)
print(np_array3)
type(np_array3)

[ 1.1 23.3 21.3]


numpy.ndarray

In [28]:
# initial placeholders in numpy arrays

# create numpy array of 0
np_array4 = np.zeros((2,6)) # in () shape is mentioned
print(np_array4)

# create a numpy array of ones
np_array5 = np.ones((6,2))
print(np_array5)

np_array6 = np.full((5,3),5)
print(np_array6)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [29]:
# create an identity matrix
np_array7 = np.eye(4) 
np_array7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])